-- =============================================================================
-- V1 — Schema initial
--
-- Ce schema est la traduction du diagramme docs/diagrammes/D2-modele-donnees.md.
-- D2 fait foi : toute modification ici doit etre reportee la-bas dans le meme
-- commit, et reciproquement.
--
-- SQL volontairement portable, sans extension propriétaire : les tests
-- d'integration tournent sur H2 en mode PostgreSQL, sans base locale (ENF7).
-- Les statuts sont stockes en VARCHAR avec un CHECK, et non en type ENUM
-- PostgreSQL, pour cette raison.
-- =============================================================================

CREATE TABLE formateur (
    id  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120) NOT NULL
);

CREATE TABLE promotion (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(120) NOT NULL UNIQUE,
    formateur_id BIGINT       NOT NULL REFERENCES formateur (id)
);

-- RG24 : un etudiant appartient a une seule promotion et ne marque sa presence
-- que sur une session de cette promotion.
CREATE TABLE etudiant (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(120) NOT NULL,
    promotion_id BIGINT       NOT NULL REFERENCES promotion (id)
);

-- RG1  : expiration_at = ouverture_at + 15 minutes.
-- RG2  : le code est unique. Le diagramme D2 prevoyait un index partiel
--        « UNIQUE (code) WHERE statut = 'OUVERTE' », que H2 ne sait pas creer.
--        L'unicite est donc globale : c'est une contrainte plus forte que RG2,
--        qu'elle satisfait donc, au prix de ne jamais reutiliser un code — sans
--        consequence, l'espace de tirage compte 32^6 valeurs.
-- RG14 : la cloture est irreversible, cloture_at ne redevient jamais NULL.
CREATE TABLE session (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(200) NOT NULL,
    promotion_id  BIGINT       NOT NULL REFERENCES promotion (id),
    code          VARCHAR(6)   NOT NULL UNIQUE,
    ouverture_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
    statut        VARCHAR(20)  NOT NULL,
    cloture_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_session_statut  CHECK (statut IN ('OUVERTE', 'CLOTUREE')),
    CONSTRAINT ck_session_cloture CHECK (
        (statut = 'OUVERTE'  AND cloture_at IS NULL)
     OR (statut = 'CLOTUREE' AND cloture_at IS NOT NULL)
    ),
    CONSTRAINT ck_session_expiration CHECK (expiration_at > ouverture_at)
);

-- RG3 : une presence est unique par (session, etudiant). La contrainte est en
--       base et pas seulement en Java : deux requetes simultanees passeraient
--       toutes les deux la verification applicative.
-- RG8 : source distingue le marquage par l'etudiant de l'ajout par le formateur.
CREATE TABLE presence (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL REFERENCES session (id),
    etudiant_id BIGINT      NOT NULL REFERENCES etudiant (id),
    source      VARCHAR(20) NOT NULL,
    marquee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))
);

-- RG9  : un seul exercice par (session, etudiant).
-- RG13 : maj_at porte la date du dernier remplacement de lien ; depose_at ne
--        change jamais.
CREATE TABLE exercice (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL REFERENCES session (id),
    etudiant_id BIGINT       NOT NULL REFERENCES etudiant (id),
    lien        VARCHAR(500) NOT NULL,
    statut      VARCHAR(30)  NOT NULL,
    depose_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    maj_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_exercice_statut CHECK (
        statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU', 'NON_ASSIGNE')
    )
);

-- RG15 : un exercice a exactement un relecteur, d'ou UNIQUE (exercice_id).
-- RG17 : le relecteur n'est jamais l'auteur. La regle ne peut pas s'exprimer en
--        CHECK ici (l'auteur est sur une autre table) : elle est portee par le
--        service et verifiee par un test unitaire.
-- RG18 : note entiere de 0 a 20.
-- RG19 : une relecture rendue est definitive ; rendue_at fige la note.
CREATE TABLE relecture (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT        NOT NULL UNIQUE REFERENCES exercice (id),
    relecteur_id BIGINT        NOT NULL REFERENCES etudiant (id),
    statut       VARCHAR(20)   NOT NULL,
    note         INTEGER,
    commentaire  VARCHAR(2000),
    assignee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    rendue_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_relecture_statut CHECK (statut IN ('EN_ATTENTE', 'RENDUE')),
    CONSTRAINT ck_relecture_note   CHECK (note IS NULL OR (note BETWEEN 0 AND 20)),
    CONSTRAINT ck_relecture_rendue CHECK (
        (statut = 'EN_ATTENTE' AND rendue_at IS NULL  AND note IS NULL)
     OR (statut = 'RENDUE'     AND rendue_at IS NOT NULL AND note IS NOT NULL)
    )
);

-- ENF2 : le tableau du formateur agrege par promotion. Sans ces index, chaque
-- affichage balaye l'integralite des tables.
CREATE INDEX ix_etudiant_promotion   ON etudiant  (promotion_id);
CREATE INDEX ix_session_promotion    ON session   (promotion_id);
CREATE INDEX ix_presence_session     ON presence  (session_id);
CREATE INDEX ix_presence_etudiant    ON presence  (etudiant_id);
CREATE INDEX ix_exercice_session     ON exercice  (session_id);
CREATE INDEX ix_exercice_etudiant    ON exercice  (etudiant_id);
CREATE INDEX ix_relecture_relecteur  ON relecture (relecteur_id);
