package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * V4 — Chaque exercice est relu par deux pairs différents (issues #34 et #35).
 *
 * <p>Le changement de besoin de l'étape 3 casse RG15, issue de Q6 : le client
 * demande désormais deux relecteurs par exercice, et la moyenne des deux notes.
 * La contrainte {@code UNIQUE (exercice_id)} posée par V1 l'interdit.
 *
 * <p><b>Pourquoi la table est recréée plutôt qu'altérée.</b> V1 déclarait
 * l'unicité en ligne — {@code exercice_id BIGINT NOT NULL UNIQUE} — et une
 * contrainte déclarée ainsi reçoit un nom généré par le moteur. Deux tentatives
 * plus chirurgicales ont échoué avant celle-ci, et elles méritent d'être
 * rappelées parce qu'elles paraissaient plus propres :
 *
 * <ol>
 *   <li>{@code DatabaseMetaData.getIndexInfo} donne le nom de l'<em>index</em>,
 *       pas celui de la <em>contrainte</em> : sur H2 les deux diffèrent
 *       ({@code CONSTRAINT_INDEX_5} contre {@code CONSTRAINT_5}) et le
 *       {@code DROP CONSTRAINT} échouait ;</li>
 *   <li>en lisant le bon nom dans {@code information_schema}, le
 *       {@code DROP CONSTRAINT} passait — mais H2 <b>laissait l'index unique
 *       derrière lui</b>, et c'est lui qui refusait ensuite le second
 *       relecteur.</li>
 * </ol>
 *
 * <p>Recréer la table ne dépend d'aucun nom généré et produit exactement le
 * même schéma sur les deux moteurs. Le seul point qu'elle imposait de traiter —
 * repositionner la séquence d'identité, impossible en SQL portable sans
 * connaître la valeur maximale — se règle ici, puisqu'on est en Java : on lit
 * {@code MAX(id)} et on construit l'ordre.
 *
 * <p><b>Les données existantes survivent</b>, comme l'exige l'énoncé. Les
 * relectures déjà posées sont recopiées telles quelles et gardent leur unique
 * relecteur : décision du commanditaire, une migration ne doit pas inventer de
 * données métier, et tirer au sort un second relecteur a posteriori en
 * inventerait.
 */
public class V4__deux_relecteurs_par_exercice extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connexion = context.getConnection();

        // Les données sont mises de côté dans une table sans contraintes, le
        // temps de reconstruire la vraie. H2 nomme les contraintes au niveau du
        // schéma et non de la table : créer la nouvelle avant de supprimer
        // l'ancienne ferait entrer `ck_relecture_statut` en collision avec
        // lui-même.
        executer(connexion, "CREATE TABLE relecture_sauvegarde AS SELECT * FROM relecture");
        executer(connexion, "DROP TABLE relecture");

        // RG15 révisée : l'unicité porte sur le COUPLE (exercice, relecteur).
        // Deux pairs différents peuvent relire le même exercice ; un même pair
        // ne peut pas le relire deux fois.
        executer(connexion, """
                CREATE TABLE relecture (
                    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    exercice_id  BIGINT        NOT NULL REFERENCES exercice (id),
                    relecteur_id BIGINT        NOT NULL REFERENCES etudiant (id),
                    statut       VARCHAR(20)   NOT NULL,
                    note         INTEGER,
                    commentaire  VARCHAR(2000),
                    assignee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
                    rendue_at    TIMESTAMP WITH TIME ZONE,
                    CONSTRAINT uq_relecture_exercice_relecteur UNIQUE (exercice_id, relecteur_id),
                    CONSTRAINT ck_relecture_statut CHECK (statut IN ('EN_ATTENTE', 'RENDUE')),
                    CONSTRAINT ck_relecture_note   CHECK (note IS NULL OR (note BETWEEN 0 AND 20)),
                    CONSTRAINT ck_relecture_rendue CHECK (
                        (statut = 'EN_ATTENTE' AND rendue_at IS NULL     AND note IS NULL)
                     OR (statut = 'RENDUE'     AND rendue_at IS NOT NULL AND note IS NOT NULL)
                    )
                )
                """);

        executer(connexion, """
                INSERT INTO relecture
                    (id, exercice_id, relecteur_id, statut, note, commentaire, assignee_at, rendue_at)
                SELECT id, exercice_id, relecteur_id, statut, note, commentaire, assignee_at, rendue_at
                  FROM relecture_sauvegarde
                """);

        executer(connexion, "DROP TABLE relecture_sauvegarde");

        // Les identifiants ont été recopiés explicitement : sans ce
        // repositionnement, la prochaine insertion repartirait de 1 et
        // violerait la clé primaire.
        executer(connexion,
                "ALTER TABLE relecture ALTER COLUMN id RESTART WITH " + prochainIdentifiant(connexion));

        // ENF2 — les index de V1 disparaissent avec la table, on les repose.
        executer(connexion, "CREATE INDEX ix_relecture_relecteur ON relecture (relecteur_id)");
        executer(connexion, "CREATE INDEX ix_relecture_exercice  ON relecture (exercice_id)");

        // Issue #35 — un exercice dont une seule des deux relectures est rendue
        // porte une note provisoire, d'où ce nouveau statut.
        executer(connexion, "ALTER TABLE exercice DROP CONSTRAINT ck_exercice_statut");
        executer(connexion, """
                ALTER TABLE exercice
                ADD CONSTRAINT ck_exercice_statut CHECK (
                    statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'PARTIELLEMENT_RELU',
                               'RELU', 'NON_ASSIGNE')
                )
                """);
    }

    /** {@code MAX(id) + 1}, ou 1 si la table était vide. */
    private long prochainIdentifiant(Connection connexion) throws Exception {
        try (Statement statement = connexion.createStatement();
             ResultSet resultat = statement.executeQuery(
                     "SELECT COALESCE(MAX(id), 0) + 1 FROM relecture")) {
            return resultat.next() ? resultat.getLong(1) : 1L;
        }
    }

    private void executer(Connection connexion, String sql) throws Exception {
        try (Statement statement = connexion.createStatement()) {
            statement.execute(sql);
        }
    }
}
